apiVersion: v2
name: osac-aap
description: OSAC AAP integration - bootstrap and configuration
type: application
version: 0.0.13-nightly.20260911.628c078.1.1
appVersion: 0.0.13-nightly.20260911.628c078.1.1
